### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Asxer** [gaetansenn/nuxt-loco#1]
I did all the steps that are mentioned in the documentation(actually just installed the module). And how can I use it? Will it add sub-routes? How can I get a translated record? What exactly this plugin do?

**Comment by gaetansenn** [comment]
Hello @Asxer you can check the playground for an exemple using nuxt i18n. But the idea of this plugin is to generate the i18n  json from localize. By default it will add it on static/i18n folder of your projet.

https://github.com/gaetansenn/nuxt-loco/blob/main/playground
